# Generated by Django 5.2.1 on 2025-05-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sensor', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
